import random
import re,os,requests

RESPONSES = {
    'greeting': [
        "Hello! I'm FinIQ Bot. How can I help you with stock market queries today?",
        "Hi there! I'm here to answer your stock market questions. What would you like to know?",
        "Welcome! I'm FinIQ's AI assistant. Ask me anything about stocks and investments!"
    ],
    'stock_info': [
        "To get information about a stock, please enter the ticker symbol in the search bar above. I can provide price predictions, news sentiment, and investment recommendations.",
        "You can search for any stock using its ticker symbol (e.g., AAPL for Apple, TCS.NS for TCS). I'll analyze it for you!",
        "Simply enter a stock ticker in the search box, and I'll provide detailed analysis including price predictions and news sentiment."
    ],
    'how_prediction_works': [
        "Our prediction system uses LSTM (Long Short-Term Memory) neural networks trained on 5 years of historical stock data. It analyzes patterns in price movements, trading volume, and technical indicators to forecast the next day's closing price.",
        "We employ advanced machine learning with LSTM models that consider 60 days of historical data including open, high, low, close prices, volume, and technical indicators like SMA, EMA, and RSI.",
        "The prediction model uses deep learning techniques to identify patterns in historical stock data. It's trained on thousands of data points to make informed predictions about future price movements."
    ],
    'sentiment_analysis': [
        "Our sentiment analysis uses Natural Language Processing to analyze recent news articles about stocks. We evaluate the tone and content to determine if the overall market sentiment is positive, negative, or neutral.",
        "We fetch the latest news from reliable sources and use TextBlob sentiment analysis to gauge market sentiment. This helps provide context for price predictions.",
        "Sentiment analysis examines news headlines and articles to understand how the market feels about a stock. Combined with price predictions, this gives you a comprehensive view."
    ],
    'recommendation': [
        "Our recommendations combine LSTM price predictions, model confidence scores, and news sentiment analysis. We use a weighted scoring system to provide Buy, Hold, or Sell recommendations.",
        "The recommendation engine considers multiple factors: predicted price movement, model accuracy, and market sentiment from news sources. This multi-factor analysis helps provide balanced investment insights.",
        "Recommendations are based on algorithmic analysis, not human emotion. However, always remember to do your own research and consult financial advisors before making investment decisions."
    ],
    'risk_disclaimer': [
        "Important: All predictions and recommendations are generated by AI models and should not be considered as professional financial advice. Stock markets are inherently risky, and past performance doesn't guarantee future results.",
        "Please note: This is an educational tool. Always conduct your own research, consider your risk tolerance, and consult with certified financial advisors before making investment decisions.",
        "Remember: Investing in stocks carries risk. Our predictions are based on historical data and may not account for unexpected market events. Never invest more than you can afford to lose."
    ],
    'features': [
        "FinIQ offers: 1) LSTM-based price predictions, 2) Real-time news sentiment analysis, 3) AI-powered investment recommendations, 4) Historical price charts, and 5) This helpful chatbot!",
        "Our platform features advanced stock prediction using machine learning, comprehensive news analysis, personalized recommendations, and an intuitive interface for all your stock research needs.",
        "You can use FinIQ to: predict stock prices, analyze market sentiment, get investment recommendations, track your favorite stocks, and access our AI chatbot for quick answers."
    ],
    'accuracy': [
        "Model accuracy varies by stock and market conditions. We display the R² score with each prediction to show model confidence. Typically, our models achieve R² scores above 0.90 for stable stocks.",
        "Prediction accuracy depends on market volatility and available historical data. We recommend using our predictions as one of many factors in your investment research.",
        "While our LSTM models are sophisticated, no prediction is 100% accurate. We provide transparency with metrics like R² score and MSE so you can evaluate model performance yourself."
    ],
    'stocks_supported': [
        "We support stocks from major exchanges including NSE/BSE (India), NYSE, NASDAQ. Simply enter the ticker symbol (e.g., RELIANCE.NS, AAPL, TSLA) to get started.",
        "You can analyze any stock with sufficient historical data on Yahoo Finance. Indian stocks use .NS (NSE) or .BO (BSE) suffixes, while US stocks use their standard tickers.",
        "Our system works with thousands of stocks worldwide. If a ticker is available on Yahoo Finance with at least 2 years of history, we can analyze it!"
    ],
    'getting_started': [
        "To get started: 1) Enter a stock ticker in the search box, 2) Wait for the analysis to complete, 3) Review the price prediction, news sentiment, and recommendation, 4) Use this information as part of your research!",
        "Start by searching for a stock ticker. Our system will analyze it and provide predictions, sentiment analysis, and recommendations within a few seconds.",
        "Simply type a stock ticker symbol in the search bar and hit enter. We'll handle the rest - fetching data, running predictions, analyzing news, and generating recommendations!"
    ],
    'technical_indicators': [
        "We use several technical indicators: SMA (Simple Moving Average), EMA (Exponential Moving Average), and RSI (Relative Strength Index). These help identify trends and momentum in stock prices.",
        "Our model incorporates SMA for trend direction, EMA for weighted recent prices, and RSI to identify overbought or oversold conditions. These indicators enhance prediction accuracy.",
        "Technical indicators like SMA, EMA, and RSI provide insights into price trends and momentum. Our LSTM model learns from these patterns to make more informed predictions."
    ],
    'default': [
        "I'm not sure I understand. You can ask me about stock predictions, how our models work, sentiment analysis, recommendations, or general stock market questions.",
        "That's an interesting question! I can help you with topics like stock predictions, our LSTM model, news sentiment analysis, investment recommendations, and platform features.",
        "I'd be happy to help! Try asking about how predictions work, what stocks we support, or how to use FinIQ effectively."
    ]
}

KEYWORDS = {
    'greeting': ['hello', 'hi', 'hey', 'greetings', 'good morning', 'good afternoon', 'good evening'],
    'stock_info': ['stock info', 'search stock', 'find stock', 'analyze stock', 'check stock'],
    'how_prediction_works': ['how prediction', 'how does prediction', 'prediction work', 'lstm', 'model work', 'algorithm'],
    'sentiment_analysis': ['sentiment', 'news analysis', 'sentiment analysis', 'market sentiment'],
    'recommendation': ['recommendation', 'should i buy', 'should i sell', 'invest', 'buy or sell'],
    'risk_disclaimer': ['risk', 'disclaimer', 'is it safe', 'guarantee', 'financial advice'],
    'features': ['features', 'what can', 'capabilities', 'what does finiq'],
    'accuracy': ['accuracy', 'how accurate', 'reliable', 'trust', 'confidence'],
    'stocks_supported': ['which stocks', 'supported stocks', 'what stocks', 'available stocks'],
    'getting_started': ['how to start', 'getting started', 'how to use', 'tutorial'],
    'technical_indicators': ['technical indicators', 'sma', 'ema', 'rsi', 'indicators']
}


def get_chatbot_response(message, context=None):
    """Generate chatbot response based on user message"""
    try:
        message_lower = message.lower()
        
        matched_category = 'default'
        best_len = 0
        for category, keywords in KEYWORDS.items():
            for kw in keywords:
                if re.search(rf'\b{re.escape(kw)}\b', message_lower) and len(kw) > best_len:
                    matched_category = category
                    best_len = len(kw)
        
        if matched_category == 'default' and HF_TOKEN:
            try:
                return {'response': llm_response(message, context),
                        'category': 'llm',
                        'suggestions': get_suggestions('default')}
            except Exception as e:
                print(f"LLM error: {e}")
                
        responses = RESPONSES.get(matched_category, RESPONSES['default'])
        response_text = random.choice(responses)
        
        if context and 'ticker' in context:
            ticker = context['ticker']
            if 'stock' in message_lower or 'ticker' in message_lower:
                response_text += f"\n\nI see you're interested in {ticker}. Use the search function to get detailed analysis!"
        
        return {
            'response': response_text,
            'category': matched_category,
            'suggestions': get_suggestions(matched_category)
        }
        
    except Exception as e:
        return {
            'response': "I apologize, but I encountered an error processing your message. Please try rephrasing your question.",
            'category': 'error',
            'suggestions': [
                "How do predictions work?",
                "What stocks are supported?",
                "How to get started?"
            ]
        }


def get_suggestions(category):
    """Get follow-up question suggestions"""
    suggestions_map = {
        'greeting': [
            "How do stock predictions work?",
            "What features does FinIQ offer?",
            "How accurate are the predictions?"
        ],
        'stock_info': [
            "How does sentiment analysis work?",
            "What's the recommendation system?",
            "Which stocks are supported?"
        ],
        'how_prediction_works': [
            "What technical indicators are used?",
            "How accurate are predictions?",
            "What is LSTM?"
        ],
        'sentiment_analysis': [
            "How are recommendations generated?",
            "What news sources do you use?",
            "How does NLP work?"
        ],
        'recommendation': [
            "What factors affect recommendations?",
            "How should I use recommendations?",
            "What are the risk disclaimers?"
        ],
        'default': [
            "How to get started?",
            "What are FinIQ's features?",
            "Tell me about predictions"
        ]
    }
    
    return suggestions_map.get(category, suggestions_map['default'])

HF_TOKEN = os.getenv('HF_TOKEN')
CHAT_URL = "https://router.huggingface.co/v1/chat/completions"

SYSTEM = (
    "You are FinIQ's assistant, helping users with stock market and investing questions. "
    "Be concise. Never give personalised financial advice; remind users to do their own "
    "research. If asked about a specific stock, tell them to use the search bar for analysis."
)

def llm_response(message, context=None):
    ctx = f"\n\nUser is currently viewing: {context.get('ticker')}" if context and context.get('ticker') else ""
    r = requests.post(CHAT_URL,
        headers={"Authorization": f"Bearer {HF_TOKEN}"},
        json={
            "model": "meta-llama/Llama-3.1-8B-Instruct",
            "messages": [
                {"role": "system", "content": SYSTEM + ctx},
                {"role": "user", "content": message},
            ],
            "max_tokens": 300,
        },
        timeout=45)
    r.raise_for_status()
    return r.json()["choices"][0]["message"]["content"]


